### ISSUE TITLE
Model 802: SOC Incorrect Type

### ISSUE THREAD

**Issue by kenny-peak-energy** [bikeshedder/sunspec#13]
Per my comment on the file. I believe this should be an `Option<u16>`.
```
    /// State of Charge
    ///
    /// State of charge, expressed as a percentage.
    ///
    /// Notes: Measurement.
    pub soc: u16,
```

**Comment by bikeshedder** [comment]
The SoC field is marked as mandatory in the JSON model:

```json
            {
                "desc": "State of charge, expressed as a percentage.",
                "label": "State of Charge",
                "mandatory": "M",
                "name": "SoC",
                "sf": "SoC_SF",
                "size": 1,
                "type": "uint16",
                "units": "%WHRtg"
            },
```

https://github.com/sunspec/models/blob/241057a11d8cd82ca1c2c7e69a7eb4b210169bb1/json/model_802.json#L112-L121

I just checked the SMDX (XML) model file and it's been mandatory ever since:

```xml
      <point id="SoC" offset="9" type="uint16" sf="SoC_SF" units="%WHRtg" mandatory="true" />
```

https://github.com/sunspec/models/blob/a1184356743f7a2673b2a58d633c3d884b6a04ba/smdx/smdx_00802.xml#L14C7-L14C94

Just to be sure I also checked in the `SunSpec_Information_Model_Referenc_20211209.xls` file:

![image](https://github.com/user-attachments/assets/f1d37365-621c-4584-9d60-168d25948f98)

---

Unless the spec is wrong this really should be a `u16` and not an `Option<u16>`.

**Comment by bikeshedder** [comment]
I just opened a new issue about parsing invalid model data:

-  #16 

Is this maybe what you were looking for?

**Comment by bikeshedder** [comment]
I'll close this issue a `invalid` then. :+1:

Ticket #16 now tracks the feature of parsing invalid model data. While I think it's going to cause a lot of troubles when parsing invalid data it shouldn't be impossible. I just don't have a great idea on what's necessary here.
